In [1]:
import scanpy as sc

In [ ]:
def add_cell_types_grouped(adata, group):
    if group == "DLBCL_2nd_level_granularity":
        adata.obs["cell_types_grouped_DLBCL_2nd_level_granularity"] = adata.obs["celltype_level2_scanvi"]
        return adata, None

In [4]:
adata = sc.read("/home/owkin/data/dataset-1df11f03-9587-49f9-a34d-cb15a4b72b6a/v2/dataset_level/dataset-1df11f03-9587-49f9-a34d-cb15a4b72b6a/merge_samples/sc_merged_annotated.h5ad")

/home/owkin/.local/conda/envs/deepdeconv/lib/python3.9/site-packages/anndata/_core/anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [5]:
adata.shape

(139475, 16590)

In [6]:
adata.obs.columns

Index(['orig.ident', 'percent_reads_mt', 'percent_reads_ribo',
       'percent_reads_hb', 'doublet_score_scdblfinder',
       'doublet_predicted_scdblfinder', 'seurat_clusters',
       'seurat_clusters_res_0.1', 'seurat_clusters_res_0.2',
       'seurat_clusters_res_0.4', 'seurat_clusters_res_0.6',
       'seurat_clusters_res_0.8', 'seurat_clusters_res_1',
       'seurat_clusters_res_2', 'origin', '_scvi_batch', '_scvi_labels',
       'scanvi_score', 'celltype_level1_scanvi', 'celltype_level2_scanvi',
       'celltype_level3_scanvi', 'celltype_level4_scanvi',
       'celltype_level_custom1_scanvi', 'SCT_snn_res.0.4', 'SCT_snn_res.2',
       'seurat_clusters_heterogeneity', 'seurat_clusters_res_1.5',
       'seurat_clusters_res_2.5', 'seurat_clusters_res_3',
       'seurat_clusters_res_3.5', 'seurat_clusters_res_4'],
      dtype='object')

In [8]:
trial_dataset = adata.to_df()

In [9]:
trial_dataset.head()

,A1CF,A2M,A2ML1,A3GALT2,A4GALT,AAAS,AACS,AADAC,AADACL2,AADAT,...,TNP1,C1QL2,CMTM5,QRFPR,SLITRK3,HS3ST4,IGFL3,OR56A5,FSCB,PRSS38
CH_D_114a.AAACAAGCAAGTTGGCACTACTCA-1,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CH_D_114a.AAACAAGCACCATCATACTACTCA-1,0.0,0.000000,0.0,0.0,0.0,0.693147,0.693147,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CH_D_114a.AAACAAGCAGCAAGCTACTACTCA-1,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CH_D_114a.AAACAAGCAGCCTATTACTACTCA-1,0.0,1.386294,0.0,0.0,0.0,0.000000,0.693147,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CH_D_114a.AAACAAGCATAGGCGTACTACTCA-1,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
adata.obs.head()

,orig.ident,percent_reads_mt,percent_reads_ribo,percent_reads_hb,doublet_score_scdblfinder,doublet_predicted_scdblfinder,seurat_clusters,seurat_clusters_res_0.1,seurat_clusters_res_0.2,seurat_clusters_res_0.4,...,celltype_level4_scanvi,celltype_level_custom1_scanvi,SCT_snn_res.0.4,SCT_snn_res.2,seurat_clusters_heterogeneity,seurat_clusters_res_1.5,seurat_clusters_res_2.5,seurat_clusters_res_3,seurat_clusters_res_3.5,seurat_clusters_res_4
CH_D_114a.AAACAAGCAAGTTGGCACTACTCA-1,CH_D_114a,3.397996,0.0,0.111481,0.003508,0,0,0,0,0,...,T_CD8_nos,T_CD8,0,0,0,3,2,67,50,50
CH_D_114a.AAACAAGCACCATCATACTACTCA-1,CH_D_114a,8.734747,0.0,0.021968,0.105918,0,45,6,7,8,...,Tu_CH_D_114a_c04,Tu_CH_D_114a_c04,5,45,5,39,45,51,49,51
CH_D_114a.AAACAAGCAGCAAGCTACTACTCA-1,CH_D_114a,2.355455,0.0,0.000000,0.120874,0,0,0,0,0,...,T_CD8_nos,T_CD8,0,0,0,3,2,67,50,50
CH_D_114a.AAACAAGCAGCCTATTACTACTCA-1,CH_D_114a,2.441788,0.0,0.035948,0.026952,0,18,4,3,3,...,Fibro_nos,Fibroblast,8,18,8,16,68,33,35,78
CH_D_114a.AAACAAGCATAGGCGTACTACTCA-1,CH_D_114a,1.829818,0.0,0.000000,0.000687,0,0,0,0,0,...,T_CD8_nos,T_CD8,0,0,0,3,2,3,4,5

In [11]:
adata.obs.columns

Index(['orig.ident', 'percent_reads_mt', 'percent_reads_ribo',
       'percent_reads_hb', 'doublet_score_scdblfinder',
       'doublet_predicted_scdblfinder', 'seurat_clusters',
       'seurat_clusters_res_0.1', 'seurat_clusters_res_0.2',
       'seurat_clusters_res_0.4', 'seurat_clusters_res_0.6',
       'seurat_clusters_res_0.8', 'seurat_clusters_res_1',
       'seurat_clusters_res_2', 'origin', '_scvi_batch', '_scvi_labels',
       'scanvi_score', 'celltype_level1_scanvi', 'celltype_level2_scanvi',
       'celltype_level3_scanvi', 'celltype_level4_scanvi',
       'celltype_level_custom1_scanvi', 'SCT_snn_res.0.4', 'SCT_snn_res.2',
       'seurat_clusters_heterogeneity', 'seurat_clusters_res_1.5',
       'seurat_clusters_res_2.5', 'seurat_clusters_res_3',
       'seurat_clusters_res_3.5', 'seurat_clusters_res_4'],
      dtype='object')